service:
  name: custom-svc-deployment
  identifier: customsvcdeployment
  orgIdentifier: default
  projectIdentifier: Pipeline_22320
  serviceDefinition:
    spec:
      customDeploymentRef:
        templateRef: MyCustomDeployment
        versionLabel: v1
    type: CustomDeployment
