apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crd2s.example.com
  annotations:
    meta.helm.sh/release-name: release-c8ca1b
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  group: example.com
  names:
    kind: CRD2
    listKind: CRD2List
    plural: crd2s
    singular: crd2
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: string