pipeline:
  name: OPA Case Remote Pipeline
  identifier: OPA_Case_Remote_Pipeline
  projectIdentifier: Pipeline_22320
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: O
        identifier: O
        description: abc-defxxx
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nginxlocal
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: opacase
            deployToAll: false
            infrastructureDefinitions:
              - identifier: opainfra2
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        timeout: 1w
