service: fd-hello-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: production
  deploymentBucket:
    name: fd-hello-sls-v3-deployment-bucket
    serverSideEncryption: AES256

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

# plugins:
#   - serverless-offline
