apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: routes.route.openshift.io
spec:
  group: route.openshift.io
  names:
    kind: Route
    listKind: RouteList
    plural: routes
    singular: route
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                path:
                  type: string
                port:
                  type: object
                  properties:
                    targetPort:
                      type: string
                tls:
                  type: object
                  properties:
                    termination:
                      type: string
                to:
                  type: object
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
            status:
              type: object