service: fd-hello-sls

frameworkVersion: '4.17.0'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: production

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

# extensions:
#   serverless-offline:
#     enabled: true
