apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.myapp.name }}
spec:
  replicas: {{ .Values.myapp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.myapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.myapp.name }}
    spec:
      containers:
        - name: myapp
          image: {{ .Values.myapp.image }}
          ports:
            - containerPort: 80