apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  {{ .Values.name }}-vs
spec:
  hosts:
    - {{ .Values.name }}-vs
  http:
    - route:
        - destination:
            host: {{ .Values.name }}-vs
            subset: v1
          weight: 90
        - destination:
            host: {{ .Values.name }}-vs
            subset: v2
          weight: 10