harness_account_id = "<+pipeline.variables.accountId>"
harness_api_key    = "<+pipeline.variables.apiKey>"
org_id             = "default"
project_id         = "FernandoD"
service_id         = "<+pipeline.variables.serviceId>"
service_name       = "<+pipeline.variables.serviceName>"
