apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crd1s.example.com
spec:
  group: example.com
  names:
    kind: CRD1
    listKind: CRD1List
    plural: crd1s
    singular: crd1
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                value:
                  type: string