apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vs-v1
  namespace: harness-delegate-ng
  labels:
    app: nginx-vs
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-vs
      version: v1
  template:
    metadata:
      labels:
        app: nginx-vs
        version: v1
    spec:
      containers:
        - name: nginx-vs
          image: nginx:1.21
          ports:
            - containerPort: 80