apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vs-v2
  namespace: harness-delegate-ng
  labels:
    app: nginx-vs
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vs
      version: v2
  template:
    metadata:
      labels:
        app: nginx-vs
        version: v2
    spec:
      containers:
        - name: nginx-vs
          image: nginx:1.25
          ports:
            - containerPort: 80