apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: harness-delegate-ng
spec:
  hosts:
    - nginx-vs
  http:
    - route:
        - destination:
            host: nginx-vs
            subset: v1
          weight: 90
        - destination:
            host: nginx-vs
            subset: v2
          weight: 10